[package]
name = "uniws-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
winnow = "0.7.11"
rfd = "0.15.3"

[dependencies.iced]
version = "0.13.1"
features = ["tokio"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dev-dependencies]
pretty_assertions = "1.4.1"
